CREATE DATABASE PC3;
SHOW DATABASES;

CREATE TABLE CREATED_EVENTS
(
RUN_ID BIGINT NOT NULL,
SCHED_TIME FLOAT,
LOC_X FLOAT,
LOC_Y FLOAT,
LOC_Z FLOAT,
RADIUS FLOAT
);

CREATE TABLE DETECTED_EVENTS
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
DETECT_TIME FLOAT,
LOC_X FLOAT,
LOC_Y FLOAT,
LOC_Z FLOAT
);

CREATE TABLE SENSOR_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
MESSAGE_TYPE VARCHAR(100),
MESSAGE_SIZE BIGINT,
EVENT_TIME FLOAT
);

CREATE TABLE SINK_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
PACKET_TYPE VARCHAR(20),
MESSAGE_TYPE VARCHAR(100),
PACKET_SIZE BIGINT,
EXPECTED_SIZE BIGINT,
FROM_IP VARCHAR(20),
VIA_IP VARCHAR(20),
TO_IP VARCHAR(20),
EVENT_TIME FLOAT
);

CREATE TABLE COLL_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
PACKET_TYPE VARCHAR(20),
MESSAGE_TYPE VARCHAR(100),
PACKET_SIZE BIGINT,
EXPECTED_SIZE BIGINT,
FROM_IP VARCHAR(20),
TO_IP VARCHAR(20),
EVENT_TIME FLOAT
);

CREATE TABLE PACKET_DROP
(
RUN_ID BIGINT NOT NULL,
PACKET_TYPE VARCHAR(20),
EVENT_TIME FLOAT
);

