CREATE DATABASE PC3;
SHOW DATABASES;

DROP TABLE PC3.CREATED_EVENTS;
DROP TABLE PC3.DETECTED_EVENTS;
DROP TABLE PC3.SENSOR_TRACE;
DROP TABLE PC3.SINK_TRACE;
DROP TABLE PC3.COLL_TRACE;
DROP TABLE PC3.PACKET_DROP;
DROP TABLE PC3.EVENT_DELAY;

CREATE TABLE PC3.CREATED_EVENTS
(
RUN_ID BIGINT NOT NULL,
EVENT_ID INT,
SCHED_TIME FLOAT,
LOC_X FLOAT,
LOC_Y FLOAT,
LOC_Z FLOAT,
RADIUS FLOAT
);

CREATE TABLE PC3.DETECTED_EVENTS
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
DETECT_TIME FLOAT,
LOC_X FLOAT,
LOC_Y FLOAT,
LOC_Z FLOAT
);

CREATE TABLE PC3.SENSOR_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
MESSAGE_TYPE VARCHAR(100),
MESSAGE_SIZE BIGINT,
EVENT_TIME FLOAT
);

CREATE TABLE PC3.SINK_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
PACKET_TYPE VARCHAR(20),
MESSAGE_TYPE VARCHAR(100),
PACKET_SIZE BIGINT,
EXPECTED_SIZE BIGINT,
FROM_IP VARCHAR(20),
VIA_IP VARCHAR(20),
TO_IP VARCHAR(20),
EVENT_TIME FLOAT
);

CREATE TABLE PC3.COLL_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
PACKET_TYPE VARCHAR(20),
MESSAGE_TYPE VARCHAR(100),
PACKET_SIZE BIGINT,
EXPECTED_SIZE BIGINT,
FROM_IP VARCHAR(20),
TO_IP VARCHAR(20),
EVENT_TIME FLOAT
);

CREATE TABLE PC3.PACKET_DROP
(
RUN_ID BIGINT NOT NULL,
PACKET_TYPE VARCHAR(20),
EVENT_TIME FLOAT
);

CREATE TABLE PC3.EVENT_DELAY
(
RUN_ID BIGINT NOT NULL,
EVENT_ID INT,
SCHED_TIME FLOAT,
SENSED_TIME FLOAT,
COLLECT_TIME FLOAT,
SINK_TIME FLOAT,
SUMMARY_IND CHAR(1) 
);
