
CREATE DATABASE PC3;
SHOW DATABASES;
USE PC3
DROP TABLE CREATED_EVENTS;
DROP TABLE DETECTED_EVENTS;
DROP TABLE SENSOR_TRACE;
DROP TABLE SINK_TRACE;
DROP TABLE COLL_TRACE;
DROP TABLE PACKET_DROP;
DROP TABLE EVENT_DELAY;

CREATE TABLE CREATED_EVENTS
(
RUN_ID BIGINT NOT NULL,
EVENT_ID INT,
SCHED_TIME FLOAT,
LOC_X FLOAT,
LOC_Y FLOAT,
LOC_Z FLOAT,
RADIUS FLOAT
);

CREATE TABLE DETECTED_EVENTS
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
DETECT_TIME FLOAT,
LOC_X FLOAT,
LOC_Y FLOAT,
LOC_Z FLOAT
);

CREATE TABLE SENSOR_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
MESSAGE_TYPE VARCHAR(100),
MESSAGE_SIZE BIGINT,
EVENT_TIME FLOAT
);

CREATE TABLE SINK_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
PACKET_TYPE VARCHAR(20),
MESSAGE_TYPE VARCHAR(100),
PACKET_SIZE BIGINT,
EXPECTED_SIZE BIGINT,
FROM_IP VARCHAR(20),
VIA_IP VARCHAR(20),
TO_IP VARCHAR(20),
EVENT_TIME FLOAT
);

CREATE TABLE COLL_TRACE
(
RUN_ID BIGINT NOT NULL,
NODE_ID INT,
PACKET_TYPE VARCHAR(20),
MESSAGE_TYPE VARCHAR(100),
PACKET_SIZE BIGINT,
EXPECTED_SIZE BIGINT,
FROM_IP VARCHAR(20),
TO_IP VARCHAR(20),
EVENT_TIME FLOAT
);

CREATE TABLE PACKET_DROP
(
RUN_ID BIGINT NOT NULL,
PACKET_TYPE VARCHAR(20),
EVENT_TIME FLOAT
);

CREATE TABLE EVENT_DELAY
(
RUN_ID BIGINT NOT NULL,
EVENT_ID INT,
SCHED_TIME FLOAT,
SENSED_TIME FLOAT,
COLLECT_TIME FLOAT,
SINK_TIME FLOAT,
SUMMARY_IND CHAR(1) 
);

CREATE VIEW RUN_RESULTS AS 
select run_id, event_id, min(sched_time), min(sensed_time) Sensed, ' ' Collected, ' ' Delivered 
from EVENT_DELAY where sensed_time>0 group by run_id, event_id  
union 
select run_id, event_id, min(sched_time), ' ' Sensed,  min(collect_time) Collected, ' ' Delivered 
from EVENT_DELAY where collect_time>0 group by run_id, event_id 
union 
select run_id, event_id, min(sched_time), ' ' Sensed, ' ' Collected, min(sink_time) Delivered 
from EVENT_DELAY where sink_time>0 group by run_id, event_id 
order by 1, 3, 4 desc, 5 desc, 6 desc;

