# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

#def configure(conf):
    #conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')
    
def build(bld):
    module = bld.create_ns3_module('venas', ['core'])
    module.lib = ['boost_system', 'boost_filesystem']

    module.source = [
        'model/venas.cc',
        'model/location.cc',
        'helper/venas-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('venas')
    module_test.source = [
        'test/venas-test-suite.cc',
        'test/location-test-suite.cc'
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'venas'
    headers.source = [
        'model/venas.h',
        'model/location.h',
        'helper/venas-helper.h',
        ]

    #module.use.extend(['boost_system', 'boost_filesystem'])

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

